CREATE TABLE IF NOT EXISTS muscles (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    parent_id BIGINT REFERENCES muscles(id) ON DELETE CASCADE,
    muscle_group VARCHAR NOT NULL,
    name VARCHAR UNIQUE NOT NULL,
    simple_name VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
)
